### ISSUE TITLE
Request for appending others Single Cell Visualizers to the current list.

### ISSUE THREAD

**Issue by vd4mmind** [praneet1988/Explore-Single-cell-Resources-and-Databases#1]
Hi Praneet,

There is a new paper that was published few weeks back. I think this will also be a great addition to this resource. 

I think I do not see it currently in your aggregator app. How about even adding this?

Web browser: http://bis.zju.edu.cn/HCL/index.html

I mentioned briefly about it in my LinkedIn post: https://www.linkedin.com/posts/vivek-das-m-sc-ph-d-b1110b25_construction-of-a-human-cell-landscape-at-activity-6649488205743816704-fIUT

Let me know if this can be added as another resource?

Kind regards,
Vivek

**Comment by praneet1988** [comment]
Thank you for letting me know I will add this to the page.

Many Thanks,
Praneet
